sudo: false
language: java

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

install: true
script: ./mvnw test --show-version --batch-mode --errors

jobs:
  include:
    - stage: "Release"
      if: branch = master AND type = push AND tag IS present
      script: skip
      deploy:
        provider: script
        script: ./mvnw deploy --show-version --batch-mode --errors --settings .travis/settings.xml -Drevision=$TRAVIS_TAG
        on:
          jdk: oraclejdk8
          repo: pavel-github/showcase-maven-travis-release
