sudo: false
language: java

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

install: true
script: ./mvnw test --show-version --batch-mode --errors

jobs:
  include:
    - stage: "release"
      script: true
      deploy:
        provider: script
        script: ./mvnw deploy --show-version --batch-mode --errors --settings .travis/settings.xml -Drevision=$TRAVIS_TAG
        on:
          branch: master
          jdk: oraclejdk8
          repo: pavel-github/showcase-maven-travis-release
          tags: true
