sudo: false
language: java

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

jobs:
  include:
    - stage: test
      if: type = pull_request
      jdk: oraclejdk8
      install: true
      script: ./mvnw test --show-version --batch-mode --errors

    - stage: test
      if: type = pull_request
      jdk: openjdk8
      install: true
      script: ./mvnw test --show-version --batch-mode --errors

    - stage: release
      if: type = push AND tag is present
      jdk: oraclejdk8
      install: true
      script: true
      deploy:
        provider: script
        script: ./mvnw deploy --show-version --batch-mode --errors --settings .travis/settings.xml -Drevision=$TRAVIS_TAG
        on:
          branch: master
          jdk: oraclejdk8
          repo: pavel-github/showcase-maven-travis-release
          tags: true
