sudo: false
language: java

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

install: true

jobs:
  include:
    - stage: "Tests"
      name: "against Oracle JDK"
      script: ./mvnw test --show-version --batch-mode --errors
      jdk: oraclejdk8
    - stage: "Tests"
      name: "against OpenJDK"
      script: ./mvnw test --show-version --batch-mode --errors
      jdk: openjdk8
    - stage: "Release"
      script: true
      deploy:
        provider: script
        script: ./mvnw deploy --show-version --batch-mode --errors --settings .travis/settings.xml -Drevision=$TRAVIS_TAG
        on:
          branch: master
          jdk: oraclejdk8
          repo: pavel-github/showcase-maven-travis-release
          tags: true
